### ISSUE TITLE
Not compliant to ng-messages

### ISSUE THREAD

**Issue by allenhwkim** [netceteragroup/valdr#64]
Thanks for the nice module. However, I found it does not go well with ng-messages, which is official message support of angularjs.

The following is the example .

    <br/>
    demoForm.lastName.$error : {{demoForm.lastName.$error | json}}
    <div ng-messages="demoForm.lastName.$error">
      <div ng-message="min">Min Error</div>
      <div ng-message="max">Max Error</div>
      <div ng-message="reuired">Required Error</div>
    </div>

From the above example,   demoForm.lastName.$error is very different from AngularJS error object. 

Is this intentional? or, you do not want us to use ng-messages or ng-message?

**Comment by philippd** [comment]
valdr sets ```$error``` as any other AngularJS validator does. I created a Plunker to show how valdr and ```ngMessages``` work without a problem: http://plnkr.co/edit/ctdsk9sePtUsqe9EJiNV?p=preview

If you want to let valdr handle the validation messages, you could also use valdr-messages for this as described here: https://github.com/netceteragroup/valdr#showing-validation-messages-with-valdr-messages

**Comment by allenhwkim** [comment]
Thanks for the reply.
What I say was this module creates its own valdr error instead of using ng-model error, and overwrites it.

From this [document](https://docs.angularjs.org/api/ngMessages), what I was expecting was. 

    
    myField.$error = { size : true, required : false };

But I see is

    myField.$error =  { "valdr-size": true, "valdr-required": false, "valdr": true}

If this module claims AngularJS compliant, it should not overwrite any AngularJS behaviour, but it is overwriting angularjs noModel $error object, at least I found.

I think this was your design and intentional.
If you think I don't understand your design, please discard this and leave it as "invalid"

**Comment by philippd** [comment]
Hello Allen

valdr is not overwriting anything and behaving exactly as AngularJS expects it. ```$error``` is an object with the validator name as key and therefore if the valdr size or required validator marks a field as invalid, ```valdr-size``` or ```valdr-required``` is set to true since it is a different validator than AngularJS built-in required validator.

Actually the behaviour you expected would mean that valdr had to overwrite AngularJS required and size  flags and you would not be able to combine valdr with the built-in AngularJS validation.

I updated the [Plunker](http://plnkr.co/edit/ctdsk9sePtUsqe9EJiNV?p=preview) with an ```ng-minlength``` and ```required``` in the markup to show how valdr and AngularJS validation work together and not overwrite each others errors.

**Comment by allenhwkim** [comment]
Thanks. I did not think `valdr` allows two values in a single rule. It's strange for me.
i.e., `ng-minlength` and `valdr-minLength`, `min`/`valdr-min`/`size`.
