### ISSUE TITLE
Custom Validator throwing error "$digest already in progress"

### ISSUE THREAD

**Issue by CarbonFactory** [netceteragroup/valdr#69]
```javascript
var factoryApp = angular.module('Factories');
factoryApp
  .factory('selectizeValidator', function($timeout) {
    return {
      name: 'selectizeValidator', // this is the validator name that can be referenced from the constraints JSON
      validate: function(value, args) {          
        return false;
      }
    };
  });
```

If I return `true`, it works fine. Because of this error the dropdown behaves erratically.

I went this way since selectize or ui-select is not supported AFAIK by valdr and only plain HTML select :expressionless:

**Comment by philippd** [comment]
You're right, valdr only validates plain selects by default. This is because the valdr directive only registers for inputs, selects and textareas.

From your example it is not clear to me what might be wrong. Can you please show a complete code example on Plunker? You can start by forking this simple valdr demo: http://plnkr.co/edit/AJC1YL206zmryGx31GFo?p=preview

**Comment by philippd** [comment]
please provide a plunkr and reopen if you still see this error.
