### ISSUE TITLE
Double message with input inside directive

### ISSUE THREAD

**Issue by spyhunter88** [netceteragroup/valdr#86]
I have many input controls with label, form ... that makes html file so big, so I want to populate them by a directive contain a group of div,label,input. That work good except if I have a normal input tag, it make double message. If I remove the directive, this input works normally.

See in plunk, the normal input is `lastName`, the directive populate for `firstName` and `age`.
 I don't know why it does not work on Chrome and Opera, only Firefox.

http://plnkr.co/edit/c7YJdbJGHTosDuQ0QyWR?p=preview

**Comment by B8li** [comment]
Hi @spyhunter88 ,

I've checked the provided example. The problem is how you create your directive that renders label and input (my-ng-input).

I've changed it a little bit and now is working fine.
http://plnkr.co/edit/YimMWfXKbMmIETtbiBzV?p=preview

P.S: Plunker example was not working fine on Chrome because you linked different files from GitHub. Check script links in updated plunker to see the correct usage.

Please in the future don't use issue list for support request. Check:
https://github.com/netceteragroup/valdr#support
